services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather_server
     ports:
      - "5000:5000"
     env_file:
      - ./server/.env  
    image: raniakh/weather-dashboard-server
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    container_name: weather_client
    ports:
      - "3000:8080"
    depends_on:
      - server
    image: raniakh/weather-dashboard-client
    restart: unless-stopped
