name: CI - Build and Push Weather Dashboard

on:
  pull_request:
    branches:
      - master
    types:
      - closed # closed PR

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build server image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard-server:latest .
        
      - name: Push server image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard-server:latest
       

      - name: Build  client image
        run: |
          cd client
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard-client:latest .
      

      - name: Push client image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-dashboard-client:latest
       